In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import importlib
import pickle
import aux_functions as aux
importlib.reload(aux)

<module 'aux_functions' from 'e:\\vispred\\aux_functions.py'>

In [2]:
MONKEY = 'M08'
SESSION = 'm08cat156'
STR_DETAILS = f'Session {SESSION}'

In [3]:
with open(f"session_data/{SESSION}.pkl", "rb") as file:
    df_session= pickle.load(file)
df_session

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
0,193,m08cat156spk002a,m08det155spk002a,B-5+0,726,OFC,0.0,NaN,NaN,0.27540,NaN,NaN,Focal Foveal,m08cat156,spk002a,NaN,NaN
1,194,m08cat156spk006a,m08det155spk006a,B-5+0,746,OFC,0.0,NaN,face,0.66811,NaN,NaN,Focal Foveal,m08cat156,spk006a,NaN,NaN
2,195,m08cat156spk008a,m08det155spk008a,B-5+0,756,OFC,0.0,NaN,NaN,1.00000,NaN,NaN,Focal Foveal,m08cat156,spk008a,NaN,NaN
3,196,m08cat156spk012a,m08det155spk012a,B-5+0,776,OFC,0.0,NaN,NaN,0.70578,NaN,NaN,Focal Foveal,m08cat156,spk012a,NaN,NaN
4,197,m08cat156spk014a,m08det155spk014a,B-5+0,786,OFC,0.0,NaN,face,1.00000,NaN,NaN,Focal Foveal,m08cat156,spk014a,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,609,m08cat156spk125b,m08det155spk125b,+1-5,970,V4,0.0,NaN,NaN,0.11156,NaN,NaN,Focal Foveal,m08cat156,spk125b,NaN,NaN
152,610,m08cat156spk125z,m08det155spk125z,+1-5,970,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk125z,NaN,NaN
153,611,m08cat156spk127a,m08det155spk127a,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127a,NaN,NaN
154,612,m08cat156spk127b,m08det155spk127b,+1-5,990,V4,0.0,0.0,NaN,NaN,NaN,NaN,Broad Foveal,m08cat156,spk127b,NaN,NaN


In [ ]:
df_session = df_session[(df_session['RF_type']=='Focal Foveal') | ~(df_session['RFin'].isna())]

In [ ]:
df_session['RF_type'].unique()

array(['Focal Foveal', 'Broad Foveal', 'Peripheral'], dtype=object)

In [5]:
df_session[df_session['RF_type']=='Peripheral']

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
88,546,m08cat156spk097a,m08det155spk097a,+1-5,690,V4,NaN,0.0,NaN,0.096865,"5,6,15","0,9,1,2,3,4,7,8,10,11,12,13,14,16,17,18,19,20",Peripheral,m08cat156,spk097a,NaN,NaN
89,547,m08cat156spk097z,m08det155spk097z,+1-5,690,V4,NaN,0.0,NaN,0.161360,"5,6","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk097z,NaN,NaN
93,551,m08cat156spk099a,m08det155spk099a,+1-5,710,V4,NaN,0.0,NaN,0.071550,"5,6","0,10,1,2,3,4,7,8,9,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk099a,NaN,NaN
94,552,m08cat156spk099z,m08det155spk099z,+1-5,710,V4,NaN,0.0,NaN,0.235220,"6,5","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk099z,NaN,NaN
98,556,m08cat156spk101a,m08det155spk101a,+1-5,730,V4,NaN,0.0,NaN,0.123180,"5,6","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk101a,NaN,NaN
105,563,m08cat156spk103a,m08det155spk103a,+1-5,750,V4,NaN,0.0,NaN,0.415990,"5,6","0,18,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,19,20",Peripheral,m08cat156,spk103a,NaN,NaN
111,569,m08cat156spk105a,m08det155spk105a,+1-5,770,V4,NaN,0.0,NaN,0.014790,"5,6","0,1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Peripheral,m08cat156,spk105a,NaN,NaN


In [7]:
df_session[df_session['RF_type']=='Broad Foveal']

,start,search,mapRF,grid_coord,depth,brain_area,sample,array,prefer,SI,RFin,RFout,RF_type,session,neuron_id,coreRFin,
18,1807,m08cat156spk034a,m08det155spk034a,+1+3,1686,TEO,0.0,0.0,NaN,0.004952,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",,Broad Foveal,m08cat156,spk034a,"0,2,4,5,6,12,15",NaN
19,1808,m08cat156spk034b,m08det155spk034b,+1+3,1686,TEO,0.0,0.0,NaN,-0.002620,"0,4,5,6,13,14","1,2,3,7,8,9,10,11,12,15,16,17,18,19,20",Broad Foveal,m08cat156,spk034b,"0,4,5,6,13",NaN
20,1809,m08cat156spk034c,m08det155spk034c,+1+3,1686,TEO,0.0,0.0,NaN,0.030485,"0,2,3,4,5,6,13,14","1,7,8,9,10,11,12,15,16,17,18,19,20",Broad Foveal,m08cat156,spk034c,"0,4",NaN
23,1812,m08cat156spk036a,m08det155spk036a,+1+3,1696,TEO,0.0,0.0,NaN,0.011836,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",,Broad Foveal,m08cat156,spk036a,"0,2,4,5,6,14,16",NaN
24,1813,m08cat156spk036b,m08det155spk036b,+1+3,1696,TEO,0.0,0.0,NaN,0.050764,"0,2,4,6","1,3,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20",Broad Foveal,m08cat156,spk036b,"0,2,6",NaN
25,1814,m08cat156spk036c,m08det155spk036c,+1+3,1696,TEO,0.0,0.0,NaN,-0.065521,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",,Broad Foveal,m08cat156,spk036c,"0,2,3,4,5,6",NaN
26,1815,m08cat156spk036z,m08det155spk036z,+1+3,1696,TEO,0.0,0.0,NaN,-0.014624,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",,Broad Foveal,m08cat156,spk036z,"0,1,4,5,6,9,12,13,14,15,18",NaN
27,1817,m08cat156spk038a,m08det155spk038a,+1+3,1706,TEO,0.0,0.0,NaN,0.029749,"0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18...",,Broad Foveal,m08cat156,spk038a,"0,4,5,6",NaN
38,1828,m08cat156spk043b,m08det155spk043b,+1+3,1576,TEO,0.0,0.0,house,-0.315920,"0,3,4,5,6,12,13,14,15,16,17","1,2,7,8,9,10,11,18,19,20",Broad Foveal,m08cat156,spk043b,"0,3,4,5,6,12,13,16,17",NaN
43,1833,m08cat156spk045a,m08det155spk045a,+1+3,1586,TEO,0.0,0.0,house,-0.221140,"0,1,2,3,4,5,6,12,13,14,16","7,8,9,10,11,15,17,18,19,20",Broad Foveal,m08cat156,spk045a,"0,1,3,4,5,6,12,13,14,16",NaN


In [ ]:
path_destiny = f'dados/{MONKEY}_neurons/neurons sorted' # linux
list_neuron_ids = df_session['search']
list_prefered_cat = df_session['prefer']
list_brain_area = df_session['brain_area']
list_RF_type = df_session['RF_type']

# df_trials = aux.get_df_trials(list_neuron_ids, path_destiny, list(list_prefered_cat), list(list_brain_area), list(list_RF_type), firings_cue_and_array=True)
# df_trials

## teste

In [9]:
import scipy.io as sio

In [10]:
neuron_id = list_neuron_ids[0]
trial_path = f'{path_destiny}/{neuron_id}.mat'
mat_data = sio.loadmat(trial_path)

In [39]:
len(mat_data['SearchEye'])

2786

In [66]:
mat_data['SearchEye'][10][0][2][3:6]

array([3., 0., 7.])

In [46]:
# for trial_idx, trial_data in enumerate(mat_data['TrlInfoMatrix']):
    # if mat_data['SearchEye'][trial_idx][0].shape[1] != 8:
        # continue
    # else:
        # trial_num = int(trial_data[0])

df_locs = []
for trial_idx, trial_data in enumerate(mat_data['TrlInfoMatrix']):
    if mat_data['SearchEye'][trial_idx][0].shape[1] != 8:
        continue
    else:
        for sacc_idx in range(len(mat_data['SearchEye'][trial_idx][0])):
            [sti_loc_idx, sti_loc_x, sti_loc_y] = mat_data['SearchEye'][trial_idx][0][sacc_idx][3:6]
            df_locs.append([sti_loc_idx, sti_loc_x, sti_loc_y])


In [176]:
mat_data['TrlInfoMatrix'][1][23]

6.112666666666667

In [178]:
mat_data['SearchEye'][1][0][1]#[6]

array([   2.        ,    6.1306    ,    6.24566667,   19.        ,
          7.        ,   -7.        , 1017.        ,    4.        ])

In [47]:
df_locs = pd.DataFrame(df_locs, columns = ['Idx','X','Y'])

In [59]:
df_locs_geral = df_locs.drop_duplicates().sort_values('Idx')

In [61]:
df_locs_geral.index = range(len(df_locs_geral.index))
df_locs_geral

,Idx,X,Y
0,0.0,0.0,0.0
1,1.0,7.0,0.0
2,2.0,4.0,4.0
3,3.0,0.0,7.0
4,4.0,-4.0,4.0
5,5.0,-7.0,0.0
6,6.0,-4.0,-4.0
7,7.0,0.0,-7.0
8,8.0,4.0,-4.0
9,9.0,11.0,4.0


In [83]:
def prod_int(x,y):
    return x[0]*y[0]+x[1]*y[1]
def norm(x): return np.sqrt(prod_int(x,x))
def dist(x,y):
    return norm(x-y)

In [92]:
def transform_loc(loc):
    return {
        0.0:0,
        4.0:1,
        -4.0:-1,
        7.0:2,
        -7.0:-2,
        11.0:3,
        -11.0:-3
    }[loc]

df_locs_geral['X_'] = df_locs_geral['X'].apply(transform_loc)
df_locs_geral['Y_'] = df_locs_geral['Y'].apply(transform_loc)
df_locs_geral

,Idx,X,Y,X_,Y_
0,0.0,0.0,0.0,0,0
1,1.0,7.0,0.0,2,0
2,2.0,4.0,4.0,1,1
3,3.0,0.0,7.0,0,2
4,4.0,-4.0,4.0,-1,1
5,5.0,-7.0,0.0,-2,0
6,6.0,-4.0,-4.0,-1,-1
7,7.0,0.0,-7.0,0,-2
8,8.0,4.0,-4.0,1,-1
9,9.0,11.0,4.0,3,1


In [96]:
# df_locs_geral['LOC'] =
df_LOC = {}
for idx,row in df_locs_geral.iterrows():
    df_LOC[idx] = (row['X_'],row['Y_'])
df_locs_geral['LOC'] = pd.Series(df_LOC,dtype=int)
df_locs_geral

,Idx,X,Y,X_,Y_,LOC
0,0.0,0.0,0.0,0,0,"(0, 0)"
1,1.0,7.0,0.0,2,0,"(2, 0)"
2,2.0,4.0,4.0,1,1,"(1, 1)"
3,3.0,0.0,7.0,0,2,"(0, 2)"
4,4.0,-4.0,4.0,-1,1,"(-1, 1)"
5,5.0,-7.0,0.0,-2,0,"(-2, 0)"
6,6.0,-4.0,-4.0,-1,-1,"(-1, -1)"
7,7.0,0.0,-7.0,0,-2,"(0, -2)"
8,8.0,4.0,-4.0,1,-1,"(1, -1)"
9,9.0,11.0,4.0,3,1,"(3, 1)"


In [103]:
df_locs_geral['LOC']

0       (0, 0)
1       (2, 0)
2       (1, 1)
3       (0, 2)
4      (-1, 1)
5      (-2, 0)
6     (-1, -1)
7      (0, -2)
8      (1, -1)
9       (3, 1)
10      (2, 2)
11      (1, 3)
12     (-1, 3)
13     (-2, 2)
14     (-3, 1)
15    (-3, -1)
16    (-2, -2)
17    (-1, -3)
18     (1, -3)
19     (2, -2)
20     (3, -1)
Name: LOC, dtype: object

In [101]:
df_locs_geral[df_locs_geral['LOC']==tuple(np.array([3,-1]) - np.array([2,2]))].index[0]

18

In [135]:
def vector_sacc(idx_start, idx_end):
    loc_start = np.array(df_locs_geral[df_locs_geral['Idx']==idx_start].iloc[0][['X_','Y_']],dtype=int)
    loc_end = np.array(df_locs_geral[df_locs_geral['Idx']==idx_end].iloc[0][['X_','Y_']],dtype=int)
    return loc_end-loc_start

def idx_vector_sacc(idx_start, idx_end):
    try:
        return df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(idx_start, idx_end))].iloc[0]['Idx']
    except IndexError:
        return np.nan

In [137]:
idx_vector_sacc(17,19)
# idx_vector_sacc(20,12)

9.0

In [126]:
df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(2,9))].iloc[0]['Idx']#1 
df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(3,10))].iloc[0]['Idx']#1 
df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(13,3))].iloc[0]['Idx']#1

df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(1,2))].iloc[0]['Idx']#4
df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(3,12))].iloc[0]['Idx']#4
df_locs_geral[df_locs_geral['LOC']==tuple(vector_sacc(7,6))].iloc[0]['Idx']#4


4.0

In [116]:
np.array(df_locs_geral[df_locs_geral['Idx']==10].iloc[0][['X_','Y_']],dtype=int)

array([2, 2])

In [91]:
# print(dist(np.array([0,0]),np.array([3.5,3.5])))
# print(dist(np.array([0,0]),np.array([4,4])))
# print(dist(np.array([3.5,3.5]),np.array([0,7])))
# print(dist(np.array([4,4]),np.array([0,7])))
# 
# print(dist(np.array([4,11]),np.array([0,7])))
# print(dist(np.array([3.5,10.5]),np.array([0,7])))
# 

4.949747468305833
5.656854249492381
4.949747468305833
5.0
5.656854249492381
4.949747468305833


(array([-3.5,  3.5]), array([ 3.5, -3.5]), 24.5, 24.5)

In [102]:
with open(f"pkl_aux_data\\df_locs_idx.pkl", "wb") as file:
    pickle.dump(df_locs_geral, file)

In [49]:
df_locs[df_locs['Idx']==19]

,Idx,X,Y
1,19.0,7.0,-7.0
46,19.0,7.0,-7.0
61,19.0,7.0,-7.0
86,19.0,7.0,-7.0
94,19.0,7.0,-7.0
...,...,...,...
5034,19.0,7.0,-7.0
5038,19.0,7.0,-7.0
5100,19.0,7.0,-7.0
5146,19.0,7.0,-7.0


## df trials com todas as sacadas (não só a primeira)

In [ ]:
 # OBS: spike times here stop in the END OF THE FIRST FIX!!! We can alter later for posterior analysis.
def get_df_trials(list_neuron_ids, path_destiny, list_prefered_cat, list_brain_area, list_RF_type, firings_cue_and_array=False):
    trial_num_TrialInfoIdx = 0 # Numero da trial
    trial_clue_imgid_TrialInfoIdx = 4 # Id da foto da pista
    trial_FP_on_time_TrialInfoIdx =  17 # Fixation point na tela
    trial_fix_FP_TrialInfoIdx =  18 # Macaco fixa o FP
    trial_clue_on_time_TrialInfoIdx = 19 # pista aparece
    trial_clue_off_time_TrialInfoIdx = 20 # pista desaparece
    trial_FP_back_time_TrialInfoIdx =  21 # Fixation point reaparece
    trial_array_on_time_TrialInfoIdx = 22 # array aparece
    trial_sacc_time_TrialInfoIdx = 23 # tempo do inicio da primeira sacada
    rows_df = []
    for i, neuron_id in enumerate(list_neuron_ids):
        trial_path = f'{path_destiny}/{neuron_id}.mat' 
        try:
            mat_data = sio.loadmat(trial_path)
            prefered_cat = list_prefered_cat[i]
            brain_area = list_brain_area[i]
            RF_type = list_RF_type[i]
            for trial_idx, trial_data in enumerate(mat_data['TrlInfoMatrix']):
                if mat_data['SearchEye'][trial_idx][0].shape[1] != 8:
                    continue
                else:
                    trial_num = int(trial_data[trial_num_TrialInfoIdx])
                    trial_clue_imgid = trial_data[trial_clue_imgid_TrialInfoIdx]
                    trial_FP_on_time = trial_data[trial_FP_on_time_TrialInfoIdx]
                    trial_fix_FP = trial_data[trial_fix_FP_TrialInfoIdx]
                    trial_clue_on_time = trial_data[trial_clue_on_time_TrialInfoIdx]
                    trial_clue_off_time = trial_data[trial_clue_off_time_TrialInfoIdx]
                    trial_FP_back_time = trial_data[trial_FP_back_time_TrialInfoIdx]
                    trial_array_on_time = trial_data[trial_array_on_time_TrialInfoIdx]
                    trial_sacc_time = trial_data[trial_sacc_time_TrialInfoIdx]
                    if pd.isnull(trial_sacc_time): continue
                    trial_photo_1sacc_imgid = mat_data['SearchEye'][trial_idx][0][1][6] # 0 pq ta tudo num array so, 1 primeira sacada (0 é fixacao), 6 id da foto da primeira sacada
                    trial_time_end_1fix = mat_data['SearchEye'][trial_idx][0][1][2] # 0 pq ta tudo num array so, 1 primeira sacada, 2 é tempo de finalizacao da fixacao # quando ele para de fixar o primeiro alvo (seja pq a trial acabou, seja pq ele fez uma segunda sacada). nao olharemos mais do que isso.
                    trial_time_start_1fix = mat_data['SearchEye'][trial_idx][0][1][1] # 0 pq ta tudo num array so, 1 primeira sacada, 1 é tempo de começo da fixacao # quando ele para de fixar o primeiro alvo (seja pq a trial acabou, seja pq ele fez uma segunda sacada). nao olharemos mais do que isso.
                    firings = mat_data['neuron'][(mat_data['neuron'] >= trial_FP_on_time) & (mat_data['neuron'] <= trial_time_end_1fix)] # desde o começo do FP ate o final da primeira sacada
                    clue_cathegory = get_image_cathegory(trial_clue_imgid)
                    photo_1sacc_cathegory = get_image_cathegory(trial_photo_1sacc_imgid)
                    trial_presacc_time = trial_sacc_time - trial_array_on_time
                    if firings_cue_and_array:
                        firings_cue = [item - trial_clue_on_time for item in firings] # 0 = cue onset
                        firings_array = [item - trial_array_on_time for item in firings] # 0 = array onset
                        firings = [item - trial_sacc_time for item in firings] # 0 = beggining of saccade
                        rows_df.append([neuron_id,prefered_cat,brain_area,RF_type,trial_num,trial_clue_imgid,clue_cathegory,trial_photo_1sacc_imgid,photo_1sacc_cathegory,trial_presacc_time,trial_FP_on_time,trial_fix_FP,trial_clue_on_time,trial_clue_off_time,trial_FP_back_time,trial_array_on_time,trial_sacc_time,trial_time_start_1fix,trial_time_end_1fix,firings,firings_cue,firings_array]) 
                    else:
                        firings = [item - trial_sacc_time for item in firings]
                        rows_df.append([neuron_id,prefered_cat,brain_area,RF_type,trial_num,trial_clue_imgid,clue_cathegory,trial_photo_1sacc_imgid,photo_1sacc_cathegory,trial_presacc_time,trial_FP_on_time,trial_fix_FP,trial_clue_on_time,trial_clue_off_time,trial_FP_back_time,trial_array_on_time,trial_sacc_time,trial_time_start_1fix,trial_time_end_1fix,firings]) 
        except Exception as e:
            print('ERRO!!!', neuron_id)
            print(traceback.format_exc())
    if firings_cue_and_array:
        df_trials = pd.DataFrame(rows_df, columns=['neuron','prefered','brain_area','RF_type','trial_num','clue_id','clue_cath','imgsacc_id','imgsacc_cath','pre_sacc_time','FP_on','fix_FP','clue_on','clue_off','FP_back','array_on','sacc_start','start_first_fix','end_first_fix','firings','firings_cue','firings_array'])
    else:
        df_trials = pd.DataFrame(rows_df, columns=['neuron','prefered','brain_area','RF_type','trial_num','clue_id','clue_cath','imgsacc_id','imgsacc_cath','pre_sacc_time','FP_on','fix_FP','clue_on','clue_off','FP_back','array_on','sacc_start','start_first_fix','end_first_fix','firings'])
    return df_trials


In [187]:
import traceback
from aux_functions import get_image_cathegory

def get_df_trials_all_saccs(list_neuron_ids, path_destiny, list_prefered_cat, list_brain_area, list_RF_type, list_RF_IN):
    trial_num_TrialInfoIdx = 0 # Numero da trial
    trial_cue_imgid_TrialInfoIdx = 4 # Id da foto da pista
    trial_FP_on_time_TrialInfoIdx =  17 # Fixation point na tela
    trial_fix_FP_TrialInfoIdx =  18 # Macaco fixa o FP
    trial_cue_on_time_TrialInfoIdx = 19 # pista aparece
    trial_cue_off_time_TrialInfoIdx = 20 # pista desaparece
    trial_FP_back_time_TrialInfoIdx =  21 # Fixation point reaparece
    trial_array_on_time_TrialInfoIdx = 22 # array aparece
    trial_1sacc_time_TrialInfoIdx = 23 # tempo do inicio da primeira sacada
    rows_df = []
    dicio_firings = {}
    for i, neuron_id in enumerate(list_neuron_ids):
        trial_path = f'{path_destiny}/{neuron_id}.mat' 
        try:
            mat_data = sio.loadmat(trial_path)
            prefered_cat = list_prefered_cat[i]
            brain_area = list_brain_area[i]
            RF_type = list_RF_type[i]
            RF_in = list_RF_IN[i]
            dicio_firings[neuron_id] = mat_data['neuron']
            for trial_idx, trial_data in enumerate(mat_data['TrlInfoMatrix']):
                if mat_data['SearchEye'][trial_idx][0].shape[1] != 8: # trial problematica
                    continue
                trial_1sacc_time = trial_data[trial_1sacc_time_TrialInfoIdx]
                if pd.isnull(trial_1sacc_time): continue
                trial_num = int(trial_data[trial_num_TrialInfoIdx])
                trial_cue_imgid = trial_data[trial_cue_imgid_TrialInfoIdx]
                trial_FP_on_time = trial_data[trial_FP_on_time_TrialInfoIdx]
                trial_fix_FP = trial_data[trial_fix_FP_TrialInfoIdx]
                trial_cue_on_time = trial_data[trial_cue_on_time_TrialInfoIdx]
                trial_cue_off_time = trial_data[trial_cue_off_time_TrialInfoIdx]
                trial_FP_back_time = trial_data[trial_FP_back_time_TrialInfoIdx]
                trial_array_on_time = trial_data[trial_array_on_time_TrialInfoIdx]
                cue_category = get_image_cathegory(trial_cue_imgid)
                trial_presacc_time = trial_1sacc_time - trial_array_on_time
                OFF_TIME_ANTERIOR = trial_1sacc_time
                LOC_ANTERIOR = 0
                CAT_ANTERIOR = 'FP'
                for sacc_idx, sacc_data in enumerate(mat_data['SearchEye'][trial_idx][0][1:]): # 0 pq tudo ta num grande array, 1+ pq 0 é a fixação no FP
                    sti_loc_idx = sacc_data[3] # id da localização no array (0-20)
                    image_id = sacc_data[6] # id da imagem
                    image_cat = get_image_cathegory(image_id)
                    target_on_time = sacc_data[1] # tempo de quando esse objeto foi fixado
                    target_off_time = sacc_data[2] # tempo de fim da sacada
                    rows_df.append([
                        neuron_id,
                        prefered_cat,
                        brain_area,
                        RF_type,
                        RF_in,
                        trial_num,
                        trial_cue_imgid,
                        cue_category,
                        trial_presacc_time,
                        trial_FP_on_time,
                        trial_fix_FP,
                        trial_cue_on_time,
                        trial_cue_off_time,
                        trial_FP_back_time,
                        trial_array_on_time,
                        trial_1sacc_time,
                        sacc_idx,
                        sti_loc_idx,
                        image_id,
                        image_cat,
                        OFF_TIME_ANTERIOR,
                        target_on_time,
                        target_off_time,
                        LOC_ANTERIOR,
                        CAT_ANTERIOR,
                        ])
                    OFF_TIME_ANTERIOR = target_off_time # depois de guardar a row, atualiza o tempo de Saída da sacada para o próximo
                    LOC_ANTERIOR = sti_loc_idx
                    CAT_ANTERIOR = image_cat

        except Exception as e:
            print('ERRO!!!', neuron_id) 
            print(traceback.format_exc())

    df_trials = pd.DataFrame(rows_df, columns=[
        'neuron',
        'prefered',
        'brain_area',
        'RF_type',
        'RF_in',
        'trial_num',
        'cue_id',
        'cue_cath',
        'pre_sacc_time',
        'FP_on',
        'fix_FP',
        'cue_on',
        'cue_off',
        'FP_back',
        'array_on',
        '1sacc_start',
        'sacc_num',
        'sacc_stim_loc',
        'sacc_img_id',
        'sacc_img_cath',
        'sacc_start_time',
        'fix_time',
        'fix_end_time',
        'stim_loc_anterior',
        'img_cath_anterior'
        ])
    return df_trials, dicio_firings


In [188]:
path_destiny = f'dados/{MONKEY}_neurons/neurons sorted' # linux
list_neuron_ids = df_session['search']
list_prefered_cat = df_session['prefer']
list_brain_area = df_session['brain_area']
list_RF_type = df_session['RF_type']
list_RF_in = df_session['RFin']

df_trials, dicio_firings = get_df_trials_all_saccs(list_neuron_ids, path_destiny, list(list_prefered_cat), list(list_brain_area), list(list_RF_type), list(list_RF_in))
df_trials

,neuron,prefered,brain_area,RF_type,RF_in,trial_num,cue_id,cue_cath,pre_sacc_time,FP_on,...,1sacc_start,sacc_num,sacc_stim_loc,sacc_img_id,sacc_img_cath,sacc_start_time,fix_time,fix_end_time,stim_loc_anterior,img_cath_anterior
0,m08cat156spk002a,NaN,OFC,Focal Foveal,NaN,2,3014.0,face,0.146367,4.168067,...,6.112667,0,19.0,1017.0,flower,6.112667,6.130600,6.245667,0.0,FP
1,m08cat156spk002a,NaN,OFC,Focal Foveal,NaN,2,3014.0,face,0.146367,4.168067,...,6.112667,1,18.0,1040.0,flower,6.245667,6.248400,6.251233,19.0,flower
2,m08cat156spk002a,NaN,OFC,Focal Foveal,NaN,2,3014.0,face,0.146367,4.168067,...,6.112667,2,17.0,3027.0,face,6.251233,6.254700,7.063400,18.0,flower
3,m08cat156spk002a,NaN,OFC,Focal Foveal,NaN,3,3013.0,face,0.135033,8.021567,...,10.524167,0,8.0,1012.0,flower,10.524167,10.526233,10.682500,0.0,FP
4,m08cat156spk002a,NaN,OFC,Focal Foveal,NaN,3,3013.0,face,0.135033,8.021567,...,10.524167,1,7.0,2015.0,house,10.682500,10.684533,10.824300,8.0,flower
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282451,m08cat156spk125b,NaN,V4,Focal Foveal,NaN,2778,3030.0,face,0.170167,12507.692067,...,12511.799033,0,4.0,4022.0,hand,12511.799033,12511.801167,12511.992733,0.0,FP
282452,m08cat156spk125b,NaN,V4,Focal Foveal,NaN,2778,3030.0,face,0.170167,12507.692067,...,12511.799033,1,14.0,2054.0,house,12511.992733,12511.995733,12512.185733,4.0,hand
282453,m08cat156spk125b,NaN,V4,Focal Foveal,NaN,2778,3030.0,face,0.170167,12507.692067,...,12511.799033,2,15.0,3030.0,face,12512.185733,12512.189700,12512.355933,14.0,house
282454,m08cat156spk125b,NaN,V4,Focal Foveal,NaN,2778,3030.0,face,0.170167,12507.692067,...,12511.799033,3,16.0,1004.0,flower,12512.355933,12512.358100,12512.365300,15.0,face


In [184]:
dicio_firings['m08cat156spk002a']

array([[1.44333333e-02, 1.20800000e-01, 1.27133333e-01, ...,
        1.25412362e+04, 1.25412391e+04, 1.25412561e+04]])